Repository anitab-org/mentorship-flutter, pull requests merged in 2020-07, with the labels that each got.

#103 feat: Maintenance update
  lib/screens/home/pages/relation/relation_page.dart
  lib/screens/register/register_screen.dart
  lib/screens/settings/settings_screen.dart
Labels: Category: Quality Assurance, Status: Needs Review, Type: Maintenance

#108 fix: Persist data
  lib/screens/home/home_screen.dart
  lib/screens/home/pages/members/bloc/members_page_bloc.dart
  lib/screens/home/pages/members/bloc/members_page_event.dart
  lib/screens/home/pages/members/members_page.dart
  lib/screens/home/pages/profile/bloc/profile_page_bloc.dart
  lib/screens/home/pages/profile/bloc/profile_page_event.dart
  lib/screens/home/pages/profile/profile_page.dart
  lib/screens/home/pages/relation/bloc/relation_page_bloc.dart
  lib/screens/home/pages/relation/bloc/relation_page_event.dart
  lib/screens/home/pages/relation/relation_page.dart
  lib/screens/home/pages/requests/bloc/requests_page_bloc.dart
  lib/screens/home/pages/requests/bloc/requests_page_event.dart
  lib/screens/home/pages/requests/requests_page.dart
  lib/screens/home/pages/stats/bloc/stats_page_bloc.dart
  lib/screens/home/pages/stats/bloc/stats_page_event.dart
  lib/screens/home/pages/stats/stats_page.dart
Labels: Category: Coding, Status: Needs Review, Type: Enhancement

#110 feat: add delete icon to delete a task instead of just clicking on the task tile
  lib/screens/home/pages/relation/relation_page.dart
Labels: Category: Coding, Status: Ready to Merge, Type: Enhancement

#112 Fix members page reload
  lib/screens/home/pages/members/bloc/members_page_bloc.dart
Labels: Status: Needs Testing

#92 feat: add confirm password field and show passwords feature to change password popUp
  lib/screens/settings/settings_screen.dart
Labels: Category: Coding, Category: User Interface, Status: Ready to Merge
