Repository anitab-org/mentorship-flutter, pull requests merged in 2020-09, with the labels that each got.

#117 chore: update bloc
  lib/auth/auth_bloc.dart
  lib/bloc_delegate.dart
  lib/main.dart
  lib/screens/home/bloc/home_bloc.dart
  lib/screens/home/pages/members/bloc/members_page_bloc.dart
  lib/screens/home/pages/profile/bloc/profile_page_bloc.dart
  lib/screens/home/pages/profile/profile_page.dart
  lib/screens/home/pages/relation/bloc/relation_page_bloc.dart
  lib/screens/home/pages/relation/relation_page.dart
  lib/screens/home/pages/requests/bloc/requests_page_bloc.dart
  lib/screens/home/pages/requests/requests_page.dart
  lib/screens/home/pages/stats/bloc/stats_page_bloc.dart
  lib/screens/home/pages/stats/stats_page.dart
  lib/screens/login/bloc/login_bloc.dart
  lib/screens/request_detail/bloc/request_detail_bloc.dart
  lib/screens/send_request/bloc/send_request_bloc.dart
  pubspec.lock
  pubspec.yaml
Labels: Category: Coding, Status: Needs Testing

#135 Fix for #134 delete account button removed
  lib/screens/settings/settings_screen.dart
Labels: Category: Coding, Category: User Interface, Status: Needs Testing

#130 feat: add sections in task tab
  lib/screens/home/pages/relation/relation_page.dart
Labels: Category: Coding, Status: Ready to Merge
