Repository anitab-org/mentorship-flutter, pull requests merged in 2020-08, with the labels that each got.

#114 feat: search members
  lib/remote/services/user_service.chopper.dart
  lib/remote/services/user_service.dart
  lib/screens/home/pages/members/members_page.dart
  lib/screens/home/pages/search/search_page.dart
  pubspec.lock
  pubspec.yaml
Labels: Category: User Interface, Status: Ready to Merge, Type: Enhancement

#102 Update dependencies
  .github/workflows/main.yml
  pubspec.lock
  pubspec.yaml
Labels: Category: Quality Assurance, Status: Needs Review, Type: Maintenance

#128 fix: fix debug toast from calendar
  lib/screens/send_request/send_request_screen.dart
Labels: Status: Needs Testing

#126 Update gh action
  .github/workflows/flutter-ci.yml
  .github/workflows/main.yml
Labels: Category: Quality Assurance, Status: Ready to Merge

#78 Adding setup instructions
  README.md
  docs/images/flutter_channel_beta.gif
  docs/images/flutter_dart_plugin.gif
  docs/images/flutter_device.gif
  docs/images/flutter_sdk.gif
  docs/setup-instructions.md
Labels: Status: Needs Review
