Repository anitab-org/mentorship-flutter, pull requests merged in 2020-06, with the labels that each got.

#87 feat: Add Pagination to Members Page
  android/settings_aar.gradle
  lib/remote/repositories/user_repository.dart
  lib/remote/services/auth_service.chopper.dart
  lib/remote/services/relation_service.chopper.dart
  lib/remote/services/task_service.chopper.dart
  lib/remote/services/user_service.chopper.dart
  lib/remote/services/user_service.dart
  lib/screens/home/pages/members/bloc/members_page_bloc.dart
  lib/screens/home/pages/members/bloc/members_page_state.dart
  lib/screens/home/pages/members/members_page.dart
Labels: Category: Coding, Status: Ready to Merge

#98 docs: update Commit Message Style guide link
  CONTRIBUTING.md
Labels: Status: Needs Review

#83 feat: add loading indicator when changing password and saving profile
  lib/screens/home/pages/profile/profile_page.dart
  lib/screens/home/pages/relation/relation_page.dart
  lib/screens/member_profile/member_profile.dart
  lib/screens/register/register_screen.dart
  lib/screens/send_request/bloc/send_request_bloc.dart
  lib/screens/send_request/bloc/send_request_event.dart
  lib/screens/send_request/send_request_screen.dart
  lib/screens/settings/settings_screen.dart
  lib/widgets/loading_indicator.dart
  pubspec.lock
Labels: Status: Needs Review

#99 feat: make disabled text fields appear grey on profile page
  lib/screens/home/pages/profile/profile_page.dart
Labels: Category: Coding, Category: User Interface, Status: Needs Testing
